version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: refhubuser
      POSTGRES_PASSWORD: refhubpass
      POSTGRES_DB: refhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://refhubuser:refhubpass@db:5432/refhub?sslmode=disable
    volumes:
      - .:/app
    command: ["./refhub"]

volumes:
  pgdata:
