version: "3.8"
services:
  backend:
    build:
      context: ./ 
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://refhubuser:refhubpass@localhost:5432/refhub?sslmode=disable # Adjust as needed
    depends_on:
      - db
  frontend:
    build:
      context: ./ 
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db: 
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=refhubuser
      - POSTGRES_PASSWORD=refhubpass
      - POSTGRES_DB=dbname
volumes:
  db_data: 